### ISSUE TITLE
Remove the usage of #if LINUX_VERSION_CODE

### ISSUE THREAD

**Issue by motolav** [digitalloggers/spi-gpio-custom#1]
The master branch of OpenWrt and upcoming release 20.XX will only use kernel 5.4 so any check on kernel version is unnecessary.

**Comment by szakharchenko** [comment]
Thanks for your interest in the code. It's not actively maintained; [linux-custom-gpio-patches](https://github.com/digitalloggers/linux-custom-gpio-patches) offers a more uniform (and modern, device-tree-style) way to address the matters that this repository and [i2c-gpio-custom](https://github.com/digitalloggers/i2c-gpio-custom) intend to solve.

As for the Linux version check, it stays as long as we have base systems to build against that are somewhat older than the latest OpenWrt version. Seeing how things progress, sooner or later new version checks could be needed:)
